name: TogetUp-Server-Dev CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "env/fix_ci" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: make application.yml
        env:
          APPLICATION: ${{ secrets.TOGETUP_DEV_APPLICATION }}
        run: |
          touch ./src/main/resources/application.yml
          echo "$APPLICATION" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test
