name: TogetUp-Server-Dev CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "env/CICD" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: make application.properties
      run: |
        ## create application.yml
        mkdir -p ./src/main/resources
        cd ./src/main/resources
        touch ./application.yaml
        echo "${{ secrets.TOGETUP_PROD_APPLICATION }}" >> ./application.yaml
        cat ./application.yaml
      shell: bash


    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
